In [1]:
from BatchNorm import *

2023-09-14 15:57:50.983260: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-14 15:57:51.644163: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
x = np.reshape(np.arange(24), (3, -1))
print(x.shape) # BatchSize, Channel, Height, Width
mbn = MyBatchNorm(8, 2)   
print(mbn(torch.tensor(x).float()).shape)

(3, 8)
torch.Size([3, 8])


In [3]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [4]:
np.mean(x, axis=(0), keepdims=False)

array([ 8.,  9., 10., 11., 12., 13., 14., 15.])

In [5]:
x = np.arange(24).reshape(2, 3, 2, 2)
print(x.shape) # BatchSize, Channel, Height, Width
mbn = MyBatchNorm(3, 4)   
print(mbn(torch.tensor(x).float()).shape)

(2, 3, 2, 2)
torch.Size([2, 3, 2, 2])


In [6]:
x[:,0,:,:]

array([[[ 0,  1],
        [ 2,  3]],

       [[12, 13],
        [14, 15]]])

In [7]:
x[1]

array([[[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [8]:
np.mean(x, axis=(0, 2, 3), keepdims=False)

array([ 7.5, 11.5, 15.5])

In [11]:
torch.abs(torch.max((nn.BatchNorm2d(3, affine=False)(torch.tensor(x).float()) - mbn(torch.tensor(x).float()))))

tensor(1.1921e-07, grad_fn=<AbsBackward0>)

In [32]:
x = np.arange(24).reshape(2, 3, 4)
torch.linalg.norm(torch.tensor(x).float(), dim=(1,2))

tensor([22.4944, 61.7900])

In [33]:
torch.mean(torch.tensor(x).float(), dim=(1,2))

tensor([ 5.5000, 17.5000])

In [34]:
x.shape

(2, 3, 4)

In [35]:
torch.sqrt(torch.sum(torch.tensor(x**2).float(), dim=(1,2)))

tensor([22.4944, 61.7900])

In [37]:
torch.tensor(x)[0].numel()

12